name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Tag
        env:
          TAG: echo "TAG=$(sed -n 6p pom.xml | sed -e 's/<version>//g' | sed -e 's/<\/version>//g')" >> $GITHUB_ENV
        run: ${{ env.TAG }}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            return sed -n 6p pom.xml | sed -e 's/<version>//g' | sed -e 's/<\/version>//g');
      - name: Echo
        run: echo ${{ steps.tag.outputs.result }}
