name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        run: mvn --batch-mode test
      - name: Tag
        run: sed -n 7p pom.xml | sed -e 's/<version>//g' | sed -e 's/<\/version>//g' >> tag
      - name: Use the value
        run: |
          echo "${{ tag }}"
